name: Test or Release

on:
  push:
    branches:
    - master
    tags:
    - 'v[0-9]+.*'
  pull_request:
    types:
    - opened
    - reopened
    - synchronize

jobs:
  test_or_release:
    name: Test or Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
    - name: Checkout Sources
      uses: actions/checkout@v2
    - name: Install Node
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
        registry-url: 'https://registry.npmjs.org'
    - name: Install PNPM
      uses: pnpm/action-setup@v2
      with:
        version: '>=6'
        run_install: |
          - args: [--frozen-lockfile, --no-verify-store-integrity]
    - name: Test
      run: pnpm recursive test
    - name: Publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: pnpm recursive publish
      if: startsWith(github.ref, 'refs/tags/')
    - name: Get Version
      id: get_version
      run: echo "::set-output name=version::$(echo "${{ github.ref }}" | sed 's/[^.0-9]\+//')"
      if: startsWith(github.ref, 'refs/tags/')
    - name: Describe Release
      run: |
        CHANGES=$(awk -v ver=${{ steps.get_version.outputs.version }} '/## / { if (p) { exit }; if ($2 == ver) { p=1; next } } p' CHANGES.md)
        echo "CHANGES<<EOF" >> $GITHUB_ENV
        echo "$CHANGES" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
      if: startsWith(github.ref, 'refs/tags/')
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        body: ${{ env.CHANGES }}
      if: startsWith(github.ref, 'refs/tags/')
